version: '3'

services:
  app:
    build: .
    platform: linux/amd64
    entrypoint: ./entrypoint.sh
    container_name: bankaccount-app
    ports:
      - '3000:3000'
    expose:
      - 3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    image: postgres
    build: ./database/postgres
    environment:
      POSTGRES_DB: mycontacts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
